
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  packages: !include_dir_named components/packages

# Configure a default setup of Home Assistant (frontend, api, etc)
# https://www.home-assistant.io/integrations/default_config/
default_config:
