
homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  name: Home
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# InfluxDb
influxdb:
  host: 127.0.0.1
  include:
    domains:
      - sensor

# z-wave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml
  debug: true
  autoheal: true

# Occupancy
input_select:
  occupancy:
    name: Occupancy
    options:
      - Home
      - Away
    initial: Home
    icon: mdi:home-circle

# Google Cast
cast:
  media_player:
    - host: !secret chromecast

# Sonos
sonos:
  media_player:
    hosts:
      - !secret sonos1
      - !secret sonos2
      - !secret sonos3

# Hue
hue:
  bridges:
    - host: !secret hue

# Samsung Smart TV
media_player:
  - platform: samsungtv
    host: !secret tv
    port: 8001
    name: The Frame

# Buienradar
sensor:
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windforce
      - winddirection

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
