title: My Awesome Home
views:
  - !include lovelace/home.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/media.yaml
  - !include lovelace/system_network.yaml
  # - !include lovelace/lan.yaml
resources:
  - url: /local/community/canvas-gauge-card/canvas-gauge-card.js
    type: module
