# Turn on outside lights after sunset
alias: Buiten licht aan 30 min. na zonsondergang
trigger:
  - platform: sun
    event: sunset
    offset: '+00:30:00'
condition:
  - condition: time
    after: '16:00:00'
    before: '22:00:00'
action:
  - service: light.turn_on
    entity_id: light.tuin